DjangoFlock/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.conf import settings
import views

# Uncomment the next two lines to enable the admin:
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'template_name': 'logout.html'}),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # REST API
    url(r'^api/', include('events.urls')),
    
    # User profile interface
    url(r'users/$', views.users_list),
    url(r'users/(?P<username>[^/]+)/$', views.users_instance),

    # HTML forms for accessing the REST API.
    url('^publishers/$', views.publishers_list),
    url('^publishers/new/$', views.publishers_new),
    url('^publishers/(?P<pk>[^/]+)/$', views.publishers_instance),
    url('^publishers/(?P<pk>[^/]+)/edit/$', views.publishers_instance_edit),

    url('^games/$', views.games_list),
    url('^games/new/$', views.games_new),
    url('^games/(?P<pk>[^/]+)/$', views.games_instance),
    url('^games/(?P<pk>[^/]+)/edit/$', views.games_instance_edit),

    url('^conventions/$', views.conventions_list),
    url('^conventions/new/$', views.conventions_new),
    url('^conventions/(?P<pk>[^/]+)/$', views.conventions_instance),
    url('^conventions/(?P<pk>[^/]+)/edit/$', views.conventions_instance_edit),

    url('^events/$', views.events_list),
    url('^events/new/$', views.events_new, name='events-new'),
    url('^events/(?P<pk>[^/]+)/$', views.events_instance),
    url('^events/(?P<pk>[^/]+)/edit/$', views.events_instance_edit),
    url('^events/(?P<pk>[^/]+)/join/$', views.events_instance_join),
    url('^events/(?P<pk>[^/]+)/leave/$', views.events_instance_leave),

    url('^demands/$', views.demands_list),
    url('^demands/mine/$', views.demands_list_mine),
    url('^demands/new/$', views.demands_new),
    url('^demands/(?P<pk>[^/]+)/$', views.demands_instance),
    url('^demands/(?P<pk>[^/]+)/edit/$', views.demands_instance_edit),
)

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

DjangoFlock/events/models.py
from datetime import datetime
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import post_save
from events.exceptions import EventFullError, OwnEventError
from textwrap import dedent

# Create your models here.

class Publisher(models.Model):
    name = models.CharField(max_length=50, unique=True)
    publisher_url = models.URLField(blank=True)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return "/publishers/%s/" % self.id

class Game(models.Model):
    name = models.CharField(max_length=50)
    edition = models.CharField(max_length=50, blank=True)
    publisher = models.ForeignKey(Publisher)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return "/games/%s/" % self.id

class Convention(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return "/conventions/%s/" % self.id

class Event(models.Model):
    host = models.ForeignKey(User, related_name='host')
    players = models.ManyToManyField(User, blank=True, null=True)
    game = models.ForeignKey(Game)
    convention = models.ForeignKey(Convention)
    start = models.DateTimeField()
    end = models.DateTimeField()
    min = models.IntegerField()
    max = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def add_player(self, user):
        """
        If you are already in the event, no problem.
        If you are the host or the event is full or you are not authenticated,
        then you get a bad response.
        """
        if not user.is_authenticated():
            raise ValueError
        if user == self.host:
            raise OwnEventError
        if len(self.players.all()) >= self.max:
            raise EventFullError
        if user in self.players.all():
            return
        self.players.add(user)
        self.save()
    
    def remove_player(self, user):
        """
        This method is idempotent; there's no problem with removing a user
        who's not present.
        """
        self.players.remove(user)
        self.save()
    
    def is_ready(self):
        return len(self.players.all()) >= self.min
    
    def is_ongoing(self):
        return self.start <= datetime.now() <= self.end
    
    @property
    def duration(self):
        """
        This used to return a timedelta. Now it returns a float of the number
        of hours of the event.
        
        Timedelta objects store days and seconds, so you have to take the
        seconds and divide by 60 * 60.
        """
        return (self.end - self.start).seconds / float(60 * 60)
    
    @property
    def title(self):
        return "%s with %s" % (self.game.name, self.host.username)

    def __repr__(self):
        return "<%s: %s>" % (self.__class__.__name__, self.id)
    
    def get_absolute_url(self):
        return "/events/%s/" % self.id 

class Demand(models.Model):
    user = models.ForeignKey(User)
    game = models.ForeignKey(Game)
    start = models.DateTimeField()
    end = models.DateTimeField()
    convention = models.ForeignKey(Convention)
    
    @property
    def duration(self):
        """
        This used to return a timedelta. Now it returns a float of the number
        of hours of the event.
        
        Timedelta objects store days and seconds, so you have to take the
        seconds and divide by 60 * 60.
        """
        return (self.end - self.start).seconds / float(60 * 60)

    def __repr__(self):
        return "<%s: %s>" % (self.__class__.__name__, self.id)
    
    def get_absolute_url(self):
        return "/demands/%s/" % self.id

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    active_convention = models.ForeignKey(Convention, blank=True, null=True, on_delete=models.SET_NULL)
    def __str__(self):
        return "User Profile: %s" % self.user.username

# Signals
def notify_interested_users(sender, instance, created, **kwargs):
    relevant_demands = Demand.objects.filter(
        game=instance.game,
        start__lte=instance.start,
        end__gte=instance.end
    #).exclude(
    #    user=instance.host
    )
    current_site = Site.objects.get_current()
    domain = current_site.domain
    for demand in relevant_demands:
        email = demand.user.email
        if email:
            send_mail(
                '[RPGflock] New Event!',
                dedent("""\
                There's a new event on RPGflock you may be interested in:
                
                %(title)s.
                
                To check it out, just go to http://%(domain)s%(url)s.
                """ % {'title': instance.title,
                       'domain': domain,
                       'url': instance.get_absolute_url()}),
                'no-reply@rpgflock.com',
                [email],
                fail_silently=False
            )
# Send the notifications. Just email for now.
# This signal is getting sent twice. Why?
post_save.connect(notify_interested_users, sender=Event, dispatch_uid='notify_interested_users')

# Register a callback function to create a user profile if none present.
def create_or_save_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    else:
        # Shenanigans here.
        # Because Django REST Framework assumes that an InstanceModelView uses a
        # Model, not a resource, it can't deal with a resource that flattens out
        # two models with a one-to-one relationship. This is a hackish way of
        # getting around it. I specify the fields in the UserProfile, and take
        # them off of the User, where DRF has put them, and stick them back on
        # the profile where they go. Then I throw up in my mouth a little.
        # So very not DRY.
        profile_fields = ('active_convention', )
        profile = instance.get_profile()
        for field in profile_fields:
            val = getattr(instance, field, None)
            setattr(profile, field, val)
        profile.save()
post_save.connect(create_or_save_user_profile, sender=User, dispatch_uid='create_or_save_user_profile')

templates/games/_form.html
<fieldset class="well">
{% for field in form %}
    {{ field.label_tag }}
    {{ field }}
	<div class="errors" id="{{ field.name }}_errors">
    {% for error in field.errors %}
    <br /><div class="alert alert-error">{{ error }}</div>
    {% endfor %}
    </div>
{% endfor %}
{% csrf_token %}
</fieldset>
<script type="text/javascript">
$(document).ready(function() {
{% if request.user.is_staff and not request.is_ajax %}
	$('[name=publisher]').after('<a href="#" class="btn btn-info btn-mini" id="add_publisher">new</a>');
{% endif %}
	// This fieldset *must* be in a form with the id create_game for this
	// behavior to work.
	$('#create_game').submit(function() {
		var csrfmiddlewaretoken = $(this).find('input[name=csrfmiddlewaretoken]').val();
		var data = $(this).serialize();
		$.ajax('/api/games/{% if editing %}{{ object.id }}/{% endif %}', {
			type: {% if editing %}'PUT'{% else %}'POST'{% endif %},
			data: data,
			beforeSend: function(jqXHR) {
				// Clear any old errors.
				$('.errors').html('');
				// If editing, set the CSRF token:
				if (this.type == 'PUT') {
					jqXHR.setRequestHeader('X-CSRFToken', csrfmiddlewaretoken);
				}
			},
			statusCode: {
				400: function(jqXHR, textStatus, errorThrown) {
					// Display errors
					// Parse jqXHR.responseText
					var errors = $.parseJSON(jqXHR.responseText);
					$.each(errors['field_errors'], function(key, error_list) {
						// Find appropriate error div, append each error in
						// error_list to that div.
						$.each(error_list, function(i, error_message) {
							$('#' + key + '_errors').append(
								"<div class=\"alert alert-error\">" + error_message + "</div>"
							);
						})
					});
				}{% if request.is_ajax %},
				201: function(data, textStatus, jqXHR) {
					// This assumes that this form is in a modal, and that it
					// needs to update the select with id id_game
					var new_item = $("<option value='" + data.id + "'>" + data.name + "</option>");
					$('#id_game').append(new_item);
					new_item.attr('selected', 'selected');
					$('#create_dialog').modal('hide');
				}{% endif %}
			}
		});
		return false;
	});
	// Get new publisher form via ajax call, insert it into modal.
	$('#add_publisher').click(function() {
		$.ajax('/publishers/new/', {
			type: 'GET',
			success: function(data, textStatus, jqXHR) {
				$('#create_dialog div.modal-body').html(data);
			},
			error: function(jqXHR, textStatus, errorThrown) {
				$('#create_dialog div.modal-body').html("<div class='alert alert-error'>" + textStatus + "</div>");
			},
			complete: function(jqXHR, textStatus) {
				$('#create_dialog').modal('show');
				$('#create_dialog').on('shown', function() {
					$('#create_dialog input:first').focus();
				});
			}
		});
	});
});
</script>

templates/games/edit.html
{% extends "base.html" %}

{% block title %} | Games | {{ object.name }} | Edit{% endblock %}

{% block css %}
{% endblock %}

{% block js %}
<script type="text/javascript">
$(document).ready(function() {
	$.ajaxSetup({
		statusCode: {
			200: function(data, textStatus, jqXHR){
				// When editing via the API, you get a 200
				window.location = '/games/' + data.id + '/';
			}
		}
	});
});
</script>

<script type="text/javascript">
$(document).ready(function() {
	$('#create_dialog').modal({
		show: false,
		backdrop: true,
		keyboard: true
	});
	$('#create_dialog').on('hidden', function() {
		$('#id_publisher').focus();
	});
	$('#modal_cancel').click(function() {
		$('#create_dialog').modal('hide');
	});
});
</script>
{% endblock %}

{% block main %}
<div id="create_dialog" class="modal fade">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">&times;</a>
		<h3>Create new Publisher</h3>
	</div>
	<form method="post" action="/publishers/new/" id="create_publisher" style="margin-bottom: 0px;">
	<div class="modal-body">
		<p>This form requires JavaScript to be enabled to work.</p>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn" id="modal_cancel">cancel</a>
		<input type="submit" class="btn btn-primary" id="modal_create" value="create" />
	</div>
	</form>
</div>

<h1>Edit <em>{{ object.name }}</em></h1>
<form action="{{ request.path }}" method="post" id="create_game">
	{% include "games/_form.html" %}
	<div>
		<input type="submit" value="save" class="btn btn-primary" />
		<a href=".." class="btn btn-warning">cancel</a>
	</div>
</form>
{% endblock %}

templates/games/instance.html
{% extends "base.html" %}

{% block title %} | Games | {{ object.name }}{% endblock %}

{% block css %}
{% endblock %}

{% block js %}
{% endblock %}

{% block main %}
<div class="row">
<h1 class="span8">{{ object.name }}</h1>
{% if user.is_authenticated and user.is_staff %}
<div class="span4"><a href="edit/" class="btn btn-info" style="float: right;">edit</a></div>
{% endif %}
</div>
<h2>by <a href="{{ object.publisher.get_absolute_url }}">{{ object.publisher.name }}</a></h2>
{% if object.edition %}
<div>{{ object.edition }} edition</div>
{% endif %}
{% endblock %}

templates/games/list.html
{% extends "base.html" %}

{% block title %} | Games{% endblock %}

{% block css %}
{% endblock %}

{% block js %}
{% endblock %}

{% block main %}
<div class="row">
<h1 class="span8">Games</h1>
{% if user.is_authenticated %}
<div class="span4"><a href="new/" class="btn btn-success" style="float: right;">create</a></div>
{% endif %}
</div>
<ul>
	{% for game in object %}
	<li><a href="{{ game.get_absolute_url }}">{{ game.name }}</a></li>
	{% empty %}
	<li class="empty">No games.</li>
	{% endfor %}
</ul>
{% endblock %}

templates/games/new.html
{% extends "base.html" %}

{% block title %} | Games | New{% endblock %}

{% block css %}
{% endblock %}

{% block js %}
<script type="text/javascript">
$(document).ready(function() {
	$.ajaxSetup({
		statusCode: {
			201: function(data, textStatus, jqXHR) {
				// Redirect to browser-UI address of new object
				// This is set here, rather than in the partial, so that the
				// partial can behave differently when called in an embedded
				// fashion.
				window.location = "/games/" + data.id + "/";
			}
		}
	});
});
</script>

<script type="text/javascript">
$(document).ready(function() {
	$('#create_dialog').modal({
		show: false,
		backdrop: true,
		keyboard: true
	});
	$('#create_dialog').on('hidden', function() {
		$('#id_publisher').focus();
	});
	$('#modal_cancel').click(function() {
		$('#create_dialog').modal('hide');
	});
});
</script>
{% endblock %}

{% block main %}
<div id="create_dialog" class="modal fade">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">&times;</a>
		<h3>Create new Publisher</h3>
	</div>
	<form method="post" action="/publishers/new/" id="create_publisher" style="margin-bottom: 0px;">
	<div class="modal-body">
		<p>This form requires JavaScript to be enabled to work.</p>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn" id="modal_cancel">cancel</a>
		<input type="submit" class="btn btn-primary" id="modal_create" value="create" />
	</div>
	</form>
</div>


<h1>Create Game</h1>
<form action="{{ request.path }}" method="post" id="create_game">
	{% include "games/_form.html" %}
	<div>
		<input type="submit" value="create" class="btn btn-primary" />
		<a href=".." class="btn btn-warning">cancel</a>
	</div>
</form>
{% endblock %}